version: "3"
services:
  api:
    container_name: callback_cats_api
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
    image: node:latest
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
networks:
  default:
    name: callback_api